name: The name of your action here
description: Provide a description here
author: Your name or organization here

# Define your inputs here.
inputs:
  location:
    description: Your input description here
    required: true
    default: .

# Define your outputs here.
outputs:
  manifest:
    description: Your output description here
  validation-json:
    description: The Flux schema validation result in JSON format

# Update the image repository and tag below.
runs:
  using: docker
  image: docker://ghcr.io/nyu-rts/rtc-k8s-lint:v0.9.0
  env:
    INPUT_LOCATION: ${{ inputs.location }}
